version: "3.8"
# docker-compose up && docker-compose rm -fsv # run and remove on exit

services:
  frontend:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    container_name: zadala-react
    volumes:
      - .:/usr/src/app
    build: .
    ports:
      - "3000:3000"
    stdin_open: true
    command: npm start
